ref_genome:
    #"/gsc/resources/Homo_sapiens_genomes/hg38_no_alt/genome/fasta/hg38_no_alt.fa"
    "ref/chr22.fa"
annotation_bedfile:
    "/gsc/resources/Homo_sapiens_genomes/hg38_no_alt/bed_files/hg38_no_alt_ensembl100_gene/Homo_sapiens.GRCh38.100.remapped.bed"
    #"annot/downsample.hg38.bed"
nanosim_model:
    "/projects/glchang_prj/software/NanoSim/pre-trained_models/human_NA12878_DNA_FAB49712_guppy/training"
annotation_gtf:
    "/projects/koneill_scratch/pog_tmp/ase_simulation/ref/chr22.gtf"
