snps:
    normalSNPcount: 30000 #2500000 #30000 
    tumorSNPcount: 1000 #20000 # 1000 

numASE: 50 #500
tumorContent:  0.8

rnaReads:
    readLength: 150
    percentExpressed: 0.4
    depth: 10 
    ASEfoldchange: 10 # x reads for ASE genes


simulatePhasing: FALSE # Simulates long read for phasing (takes much longer), else use perfect phasing
WASPfilter: TRUE # Use WASP filtering star alignment or Kalisto alignment
    
longRead:
    numReads: 3000000 #50000
